In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
voc_size=10000

In [4]:
one_hot_repe=[one_hot(words,voc_size) for words in sent]
one_hot_repe

[[5579, 8919, 3640, 5163],
 [5579, 8919, 3640, 1102],
 [5579, 8050, 3640, 8328],
 [5025, 3536, 7122, 2358, 5312],
 [5025, 3536, 7122, 2358, 2693],
 [2195, 5579, 7740, 3640, 6452],
 [2443, 9872, 3515, 2358]]

In [5]:
#word embedding represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np


In [7]:
sent_length=8 
embedded_docs=pad_sequences(one_hot_repe, padding='pre', maxlen=sent_length)

In [8]:
embedded_docs

array([[   0,    0,    0,    0, 5579, 8919, 3640, 5163],
       [   0,    0,    0,    0, 5579, 8919, 3640, 1102],
       [   0,    0,    0,    0, 5579, 8050, 3640, 8328],
       [   0,    0,    0, 5025, 3536, 7122, 2358, 5312],
       [   0,    0,    0, 5025, 3536, 7122, 2358, 2693],
       [   0,    0,    0, 2195, 5579, 7740, 3640, 6452],
       [   0,    0,    0,    0, 2443, 9872, 3515, 2358]], dtype=int32)

In [9]:
#feature represntaion
dim=10


In [10]:
from tensorflow.keras import Input

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[ 0.04314411,  0.02199316, -0.02360878,  0.02107766,
         -0.01620751,  0.00666722,  0.00456186,  0.00952214,
          0.04782455, -0.02951968],
        [ 0.04314411,  0.02199316, -0.02360878,  0.02107766,
         -0.01620751,  0.00666722,  0.00456186,  0.00952214,
          0.04782455, -0.02951968],
        [ 0.04314411,  0.02199316, -0.02360878,  0.02107766,
         -0.01620751,  0.00666722,  0.00456186,  0.00952214,
          0.04782455, -0.02951968],
        [ 0.04314411,  0.02199316, -0.02360878,  0.02107766,
         -0.01620751,  0.00666722,  0.00456186,  0.00952214,
          0.04782455, -0.02951968],
        [-0.01184641, -0.01271471, -0.00905798,  0.03032107,
         -0.04151572,  0.03548584,  0.02353508,  0.01306338,
          0.0168624 ,  0.01952746],
        [ 0.00704737,  0.01832397, -0.04235803, -0.02825123,
          0.00286023, -0.01926774,  0.01585374,  0.04269018,
          0.03856691,  0.04882497],
        [-0.04069976, -0.01374821,  0.01242335,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5579, 8919, 3640, 5163], dtype=int32)